# Generated by Django 6.0 on 2025-12-24 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Назва')),
                ('type', models.CharField(max_length=256, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступний')),
                ('description', models.TextField(verbose_name='Опис')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.location', verbose_name='Розташування')),
            ],
        ),
    ]
