# Generated by Django 6.0 on 2026-02-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Resource', '0002_alter_resource_description'),
        ('UserProfile', '0002_alter_userprofile_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_url', models.URLField(blank=True, default=None, max_length=1000, verbose_name='Посилання на урок')),
                ('day', models.CharField(max_length=100, verbose_name='День тижня')),
                ('number', models.PositiveIntegerField(verbose_name='Номер занятть')),
                ('study', models.PositiveIntegerField(verbose_name='Класс')),
                ('resource', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Resource.resource', verbose_name='Кабінет')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.subject', verbose_name='Предмет')),
            ],
        ),
    ]
