# Generated by Django 6.0 on 2025-12-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
        ('Resource', '0002_alter_resource_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Інформація від адміна'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Resource.resource', verbose_name="Об'єкт"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Booking.status', verbose_name='Статус'),
        ),
    ]
