# Generated by Django 6.0 on 2026-01-14 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CB', 'CreateBooking'), ('RB', 'ReadBooking'), ('UB', 'UpdateBooking')], default='RB', help_text='Введіть назву дії', max_length=100, verbose_name='Дозволена дія')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть назву предмета', max_length=100, verbose_name='Назва предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть посаду', max_length=100, verbose_name='Посада')),
                ('action', models.ManyToManyField(help_text='Оберіть дозвіл', to='UserProfile.action', verbose_name='Список дозволів')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва класу')),
                ('description', models.CharField(blank=True, default=None, max_length=256, verbose_name='Опис класу')),
                ('subjects', models.ManyToManyField(blank=True, default=None, null=True, to='UserProfile.subject', verbose_name='Список предметів')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='.', verbose_name='Аватарка')),
                ('bio', models.TextField(blank=True, default=None, null=True, verbose_name='Про себе')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Номер телефону')),
                ('classroom', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.classroom')),
                ('positions', models.ManyToManyField(blank=True, default=None, null=True, to='UserProfile.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
