# Generated by Django 6.0 on 2025-12-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(choices=[('CB', 'CreateBooking'), ('RB', 'ReadBooking'), ('UB', 'UpdateBooking')], default='RB', help_text='Введіть назву дії', max_length=100, verbose_name='Дозволена дія'),
        ),
        migrations.AlterField(
            model_name='position',
            name='action',
            field=models.ManyToManyField(help_text='Оберіть дозвіл', to='UserProfile.action', verbose_name='Список дозволів'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(help_text='Введіть посаду', max_length=100, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Введіть назву предмета', max_length=100, verbose_name='Назва предмета'),
        ),
    ]
