# Generated by Django 6.0 on 2026-01-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_userprofile_phone_number_alter_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='UserProfile.subject', verbose_name='Список предметів'),
        ),
    ]
