# Generated by Django 6.0 on 2026-01-13 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_remove_userprofile_position_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subjects',
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва класу')),
                ('description', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='Опис класу')),
                ('subjects', models.ManyToManyField(blank=True, default=None, null=True, to='UserProfile.subject', verbose_name='Список предметів')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='classroom',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.classroom'),
        ),
    ]
